### ISSUE TITLE
Cannot deploy to Cloudflare Workers Assets

### ISSUE THREAD

**Issue by austinm911** [arthelokyo/astrowind#550]
https://developers.cloudflare.com/workers/frameworks/framework-guides/astro/
 
If you follow along the example guide, create a wrangler.toml and try to deploy, I'm getting the error below. Not sure exactly where this is happening.

```
❯ nr deploy
$ astro build && wrangler pages deploy
Cannot read properties of undefined (reading 'startsWith')
  Location:
    /Users/am/Coding/example-app/node_modules/@astrojs/internal-helpers/dist/path.js:17:15
  Stack trace:
    at removeLeadingForwardSlash (file:///Users/am/Coding/example-app/node_modules/@astrojs/internal-helpers/dist/path.js:17:15)
    at injectImageEndpoint (file:///Users/am/Coding/example-app/node_modules/astro/dist/assets/endpoint/config.js:8:24)
    at async AstroBuilder.run (file:///Users/am/Coding/example-app/node_modules/astro/dist/core/build/index.js:181:23)
    at async build (file:///Users/am/Coding/example-app/node_modules/astro/dist/cli/build/index.js:29:3)
    at async cli (file:///Users/am/Coding/example-app/node_modules/astro/dist/cli/index.js:175:5)
error: script "deploy" exited with code 1
```

**Comment by prototypa** [comment]
The `startsWith` crash came from a version mismatch in the Astro 5 beta period: Astro changed the shape of `image.endpoint` and older adapters still passed the previous one. On the current template (Astro 7.3 with the current `@astrojs/cloudflare`) the build with the adapter completes, and there's a short guide in `.agents/skills/deploy-cloudflare.md`. If you hit a problem deploying with today's versions, please open a new issue with the wrangler output. Closing.
